### ISSUE TITLE
compiling issue

### ISSUE THREAD

**Issue by stevenewbold** [Jojendersie/Epsilon-Intersection#35]
Hi, I'm trying to use EI for the first time and I'm getting the following compiling error using Clang on MacOS,

```
/usr/local/include/ei/3dtypes.hpp:856:15: error: constructor for 'ei::FastFrustum' must explicitly initialize the const member 'vertices'
        EIAPI FastFrustum(const Frustum& _frustum) noexcept                          // TESTED
              ^
/usr/local/include/ei/3dtypes.hpp:853:20: note: 'vertices' declared here
        const Vec3 vertices[8]; ///< All vertices in the orderd: nlb, nlt, nrb, nlt, flb, flt, frb, frt
```

I'm currently not doing anything except trying to include 3dintersection.hpp at the moment.

**Comment by Jojendersie** [comment]
Thanks for reporting. I am trying to fix this, but there seem some more problems with constexpr.

**Comment by Jojendersie** [comment]
Hope I fixed it. Let me know if this or other things still not work.

**Comment by stevenewbold** [comment]
Thanks,  it certainly compiles now with the header included.  I'll let you know if I come across any further issues.
