### ISSUE TITLE
Missing intersects functions

### ISSUE THREAD

**Issue by redrabbit007** [Jojendersie/Epsilon-Intersection#36]
In the readme it's marked that checking if a ray intersects with a frustum is implemented, but I can't find where this is in the code. Could you point me to the ray/frustum intersect code or add this function?

**Comment by Jojendersie** [comment]
Hi redrabbit007
you are right ray/frustum doesn't exist. I found Point/Sphere/Box to Frustum. Looks like Sphere got placed wrong in the table.

Anyways, I will try to implement this within the next week. Happy that someone is using this which motivates me a lot to add some new methods.

**Comment by Jojendersie** [comment]
That was surprisingly challenging, but it passes a whole bunch of tests now. I hope I got all signs and comparison operators right for all the edge cases.

There is now a function that takes a Ray (with tmin/tmax inputs) and a Frustum and returns intersection as well as tmin and tmax of the intersection range.
I hope this is what you needed!
