### ISSUE TITLE
Unicode Characters MSVC++140

### ISSUE THREAD

**Issue by Wumpf** [Jojendersie/Epsilon-Intersection#6]
The new Microsoft c++ compiler (Visual Studio 2015 -- msvc++140) does not support variable names that start with √ and ∞.

Personally I suggest to remove the other unicode character variable names as well or at the very least make them optional (meaning that they do not occur within the library's implementations).

``include\ei\elementarytypes.hpp(84): error C3873: '0x221a': this character is not allowed as a first character of an identifier``
``include\ei\elementarytypes.hpp(86): error C3873: '0x221e': this character is not allowed as a first character of an identifier``

**Comment by Jojendersie** [comment]
I will make them optional, probably by renaming the define in the config file and using them for all such names.

**Comment by Wumpf** [comment]
There is a practical problem with the current solution of which I wasn't aware just recently:

I use epsilon as a submodule and have a custom config which I want to add to the repository. Since it is a submodule, I cannot leave it in the epsilon directories -> therefore I would need to add it to my main codebase. Because of the "details/config.inl" include within the config this is not possible! Additionally this would "pollute" my include namespace with a generic "config.hpp".

-> Would you mind renaming splitting the two files up and rename config.hpp to "epsilonconfig.hpp" or something similar? The config.inl is not really a config file after all. I suggest renaming it to "basics.hpp" and let it include "epsilonconfig.hpp" and not the other way round.

This is not super urgent, but a bit unconvenient since I don't see how I can otherwise provide a repo that just works out-of-the-box, based on submodules.

**Comment by Jojendersie** [comment]
So far, I did not understand everything. I use epsilon as submodule too and simply put the config in the ei-include directory. As far as I know it is still possible to add this file to the main repository (even if it is in a directory together with a submodule). Did not test this if it compiles out of the box, but I expect so. 

If this does not solve the problem I will try your fix, but I can't see how it solves the issue. In any way the other files will include the "epsilonconfig.hpp" which still means you need to provide it in visible range and cannot move it arbitrary around. however the proposed are changes seem good anyway, so it is likely, that I will change it soon.

**Comment by Wumpf** [comment]
From what I understand, it is not possible to change files or add files in a submodule and pushing the changes somewhere without altering the submodule's repo (or forking it every time): http://stackoverflow.com/questions/25287528/is-possible-to-add-files-inside-a-submodule-folder-to-the-parent-git-repository

Since its been I while, I also don't see how my suggestion would solve the problem....
I think the default "epsilonconfig.hpp" would need to be at a location that is not reachable by default: Like with the defaultconfig in glhelper, which is part of the repository but cannot be seen by all other files of glhelper without showing the compiler where to find it.
I admit that this worsens the "user experience" but currently I do not see how I can push custom epsilon configs into my own repository.
It would be great if you can give me a sample project if I am missing some important detail here :)
