### ISSUE TITLE
FastFrustum assignment operator incomplete

### ISSUE THREAD

**Issue by markvandieren** [Jojendersie/Epsilon-Intersection#7]
Maybe I'm doing something wrong, but the assignment operator for the FastFrustum struct doesn't seem to copy the `Vec3 vertices[8]` member.

When does it happen: I initialize a FastFrustum with dummy values, then use the assignment operator to get the actual values in.

To fix the issue I added the following line to the assignment operator:
`for (int i = 0; i < 8; ++i)	const_cast<Vec3&>(vertices[i]) = _frustum.vertices[i];`

**Comment by Jojendersie** [comment]
Oh, did not look into the Issues for a long time.

And, your are absolutely right, that the line is missing. I will add it immediately.
